services:
  ambic-be:
    container_name: ambic-be
    build: .
    restart: unless-stopped
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    networks:
      - ambic

networks:
  ambic:
    driver: bridge
